### ISSUE TITLE
option to create a PR when the claude code job completes

### ISSUE THREAD

**Issue by ryx2** [anthropics/claude-code-action#114]
Why must I go back to the issue, and then click the 'Create PR' button? I would like to have the option to auto-create the PR when the claude code job is done

**Comment by ashwin-ant** [comment]
We mention this in our [FAQ](https://github.com/anthropics/claude-code-action/blob/main/FAQ.md#why-wont-claude-create-a-pull-request):

> **Why won't Claude create a pull request?**
> Claude doesn't create PRs by default. Instead, it pushes commits to a branch and provides a link to a pre-filled PR submission page. This approach ensures your repository's branch protection rules are still adhered to and gives you final control over PR creation.

You can give Claude the ability to create a pull request by adding `mcp__github__create_pull_request` as an allowed tool. Then include an instruction in `custom_instructions` telling it to use the tool.

**Comment by leehagoodjames** [comment]
@ashwin-ant I have tried this and am still not successful in getting Claude to automatically open the PR request. 

Is there something else I should be doing?

Here is my `.github/workflows/claude.yml`

```
name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      checks: read
      repository-projects: read
      statuses: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          allowed_tools: "mcp__github__create_pull_request"
          custom_instructions: "Use the create_pull_request tool to create a pull request."
```
