### ISSUE TITLE
Internal Server Error (HTTP 500) from Anthropic's API

### ISSUE THREAD

**Issue by gaurish** [anthropics/claude-code-action#13]
### Description
I'm experiencing persistent HTTP 500 internal server errors when running the claude-code-action on my repository's pull requests. The action starts but fails with an internal error from Anthropic's API.

### Environment
- claude-code-action version: `@beta`
- Model used: `claude-3-7-sonnet@20250219`
- Using Vertex AI: `true`
- GitHub Actions runner: GitHub-hosted
- Repository type: Private
- PR size: 44 files changed (675 additions, 190 deletions)

### Steps to Reproduce
1. Created PR with changes to multiple files
2. Added workflow file with claude-code-action
3. Triggered the action automatic
4. Action initiates but fails with HTTP 500 error

### Error Message
API Error: 500 {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}

### Relevant Configuration
```yaml
Run anthropics/claude-code-action@beta
  with:
    use_vertex: true
    anthropic_model: claude-3-7-sonnet@20250219
    direct_prompt: "Please review this PR. Look at the changes and provide thoughtful feedback on:
  - Code quality and best practices
  - Potential bugs or issues
  - Suggestions for improvements or making the code simpler
  - Overall architecture and design decisions
  - compliance with solid principles
```

### Attempts to Resolve

- Have tried running the action multiple times
- The action consistently fails with the same HTTP 500 error
- I have tried with small PRs and big PR, it fails both ways. 
- All authentication credentials appear to be correctly configured

Any guidance would be greatly appreciated. I'm happy to provide additional information if needed.
