### ISSUE TITLE
Error: Expected content to be an assistant message, but got 'user' when using MCP tools

### ISSUE THREAD

**Issue by maxmetcalf12** [anthropics/claude-code-action#138]
**Describe the bug**
The Claude Code GitHub Action throws an error `Error: Expected content to be an assistant message, but got "user"` after successfully completing a PR review using MCP tools. Despite the error, the review is posted successfully, but the action fails and times out after 300 seconds.

**To Reproduce**

1. Set up claude-auto-review.yml with `allowed_tools: "mcp__github__add_pull_request_review_comment"`
2. Trigger the action by either:
   - Opening a new PR
   - Commenting `@pr-rerun-claude` on an existing PR
3. Claude successfully creates initial comment and completes the review
4. After updating the comment with review content, the error occurs
5. Action times out after 300 seconds with exit code 124

**Expected behavior**
The action should complete successfully after posting the PR review without throwing errors or timing out.

**Screenshots**
N/A - Error output included in additional context

**Workflow yml file**
```yaml
name: Claude Auto Review

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group: claude-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  auto-review:
    if: |
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@pr-rerun-claude')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@pr-rerun-claude')) ||
      (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "5"
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Following standards in our CLAUDE.md file
            - Test coverage

            Provide constructive feedback with specific suggestions for improvement.
            Your review should be concise and to the point and any code suggestions should
            be added as an inline comment on the code that is of concern.
```
**API Provider**

[X] Anthropic First-Party API (default)
[ ] AWS Bedrock
[ ] GCP Vertex

**Additional context**
The error occurs in the conversation flow after successfully using MCP tools. Here's the relevant error output:

```
✅ Created initial comment with ID: 2950054050
Successfully fetched PR #607 data
This is an open PR, checking out PR branch...
[Claude completes review and updates comment successfully]
Error: Expected content to be an assistant message, but got "user" at yS2 (file:///opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:2342:9744) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async bE5 (file:///opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:2356:8265)
Claude process timed out after 300 seconds
Error: Process completed with exit code 124.

The review is successfully posted to the PR despite the error. The issue appears to be with how the action handles the conversation state after receiving tool results from the MCP GitHub integration.
```

**Comment by ashwin-ant** [comment]
@maxmetcalf12 when did you encounter this issue? We rolled out a fix for this a few hours ago.

**Comment by maxmetcalf12** [comment]
It's happened all morning, last one was 18 minutes ago.

**Comment by mvfolino68** [comment]
Same issue. I can't say when it started because I picked up working on it after a few days.

**Comment by ashwin-ant** [comment]
Any other details you can provide? Is this happening consistently or just in certain cases?

**Comment by mvfolino68** [comment]
The Claude Code GitHub Action fails after successfully posting a review comment, with the following error:

```
Error: Expected content to be an assistant message, but got "user"
```

This occurs after Claude creates the PR comment using MCP tools like `mcp__github_file_ops__update_claude_comment`. Despite the failure, the review content appears correctly on the PR. The action then hangs and times out (exit code 124).

I suspect this may be related to previously deleted Claude comments, which could be causing the internal conversation state to mismatch expected roles.

* I am using the `beta` release of the `claude-code-action`
* I am using API key.
* The workflow is configured with a detailed `direct_prompt`
* I manually deleted old Claude review comments during testing

**Workflow configuration**:

```yaml
name: Claude PR Review

on:
  pull_request:
    types: [opened]

jobs:
  claude-review:
    if: |
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out code
        uses: <redacted>

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: "WebSearch"
          direct_prompt: <redacted>

```

**Expected behavior**:
Claude should complete the review and exit cleanly, regardless of prior comment state. Deleted or missing comments should not break the run.

**Repro steps**:

1. Set up Claude with the above workflow
2. Trigger a PR review (on PR open)
3. Ensure a previous Claude comment has been manually deleted
4. Observe error and hang after review is posted

**Error Output**:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Expected content to be an assistant message, but got "user"
    at yS2 (file:///opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:2342:9744)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bE5 (file:///opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:2356:8265)

Claude process timed out after 1800 seconds
Error: Process completed with exit code 124.
```

Later in the workflow, another attempt to fetch the Claude comment also fails:

```
Fetching issue comment 2950012687
GET /repos/redacted/redacted/issues/comments/2950012687 - 404

HttpError: Not Found - https://docs.github.com/rest/issues/comments#get-an-issue-comment
   status: 404,
   request: {
     method: "GET",
     url: "https://api.github.com/repos/redacted/redacted/issues/comments/2950012687",
     ...
   },
   response: {
     url: "https://api.github.com/repos/redacted/redacted/issues/comments/2950012687",
     status: 404,
     ...
   }
```

it's possible that there are two issues here. The original one and the missing comment error. I haven't been able to disentangle them.
