### ISSUE TITLE
Support max_turns argument

### ISSUE THREAD

**Issue by ashwin-ant** [anthropics/claude-code-action#148]
The base action exposes max_turns as an input, we should support it here

**Comment by ashwin-ant** [comment]
@claude add this. example of what it looks like

```
- name: Run Claude Code with limited turns
  uses: anthropics/claude-code-base-action@beta
  with:
    prompt: "Your prompt here"
    allowed_tools: "Bash(git:*),View,GlobTool,GrepTool,BatchTool"
    max_turns: "5" # Limit conversation to 5 turns
    anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
```

make sure to add a test and update the readme
