### ISSUE TITLE
Multiline input for allowed_tools

### ISSUE THREAD

**Issue by int128** [anthropics/claude-code-action#167]
It would be nice if `allowed_tools` accepts a multiline string.

## Problem to solve
We use this action in monorepo. When I set a lot of tools, the workflow looks ugly. For example,

```yaml
      - uses: anthropics/claude-code-action@beta
        with:
          allowed_tools:  Bash(pnpm:*),Bash(yarn:*),Bash(npm:*),Bash(go:*),Bash(make:*),Bash(bundle:*),Bash(ruby:*),Bash(poetry:*),Bash(echo:*),Bash(git:*),Bash(gh:*)
```

It would be nice if it can be delared as follows:

```yaml
      - uses: anthropics/claude-code-action@beta
        with:
          allowed_tools: |
            Bash(bundle:*)
            Bash(ruby:*)
            Bash(yarn:*)
            Bash(pnpm:*)
            #...
```
