### ISSUE TITLE
Allowed tools from the example in the README do not work

### ISSUE THREAD

**Issue by kvz** [anthropics/claude-code-action#181]
**Describe the bug**
Allowed tools from the example in the README do not work

**To Reproduce**
Add this:

```
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-opus-4-20250514
          allowed_tools: 
            - Bash(corepack yarn check)
            - Bash(corepack yarn)
            - Bash(corepack yarn add:*)
            - Bash(gh run:*)
```

Claude Code will complaint it does not have access to these tools when asked.

**Expected behavior**
It should happily run those.

**Additional context**

When I switched to this format, it did work: `allowed_tools: Bash(corepack yarn check),Bash(corepack yarn),Bash(corepack yarn add:*),Bash(gh run:*)`
