### ISSUE TITLE
feat: Settings such as allowed_tools using settings.json

### ISSUE THREAD

**Issue by takanakahiko** [anthropics/claude-code-action#189]
## Overview

Currently, the settings for `allowed_tools` and `disallowed_tools` are not affected by the contents of `.claude/settings.json`.
However, in actual usage, the values of `allowed_tools` / `disallowed_tools` often align with the `allow` / `deny` field inside `.claude/settings.json`.
Therefore, I would like to request a feature that enables these settings to be utilized by specifying the path to `.claude/settings.json`.

### Before

`.github/workflows/claude.yml`

```yaml
- uses: anthropics/claude-code-action@beta
  with:
    allowed_tools: |
      Bash(npm install)
      Bash(npm run test)
    disallowed_tools: |
      Bash(curl:*)
```

### After

`.github/workflows/claude.yml`

```yaml
- uses: anthropics/claude-code-action@beta
  with:
    settings_path: .claude/settings.json
```

`.claude/settings.json`

```json
{
  "permissions": {
    "allow": [
      "Bash(npm install)",
      "Bash(npm run test)"
    ],
    "deny": [
      "Bash(curl:*)"
    ]
  }
}
```

## Notes

* Automatically loading `.claude/settings.json` would mean that the values of `allowed_tools` could change unexpectedly for existing users. It would be best to avoid applying `.claude/settings.json` unless `settings_path` is explicitly specified (at least while in beta).
* It is necessary to consider how to handle cases where both `settings_path` and `allowed_tools` are specified at the same time.
