### ISSUE TITLE
Unable to assign claude to an issue

### ISSUE THREAD

**Issue by Djiit** [anthropics/claude-code-action#203]
Hey team, I must be missing something obvious, but I can't assign claude to an issue on a private repo (where we already use it through comment mention). What am I missing ?

**Comment by tomoish** [comment]
@Djiit 
You need to add this to your workflow configuration:
```
- uses: anthropics/claude-code-action@beta
  with:
    anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
    assignee_trigger: "claude"  # Add this line
```
And make sure your workflow triggers on assignments:
```
on:
  issues:
    types: [opened, assigned]  # Include 'assigned'
```
