### ISSUE TITLE
Support GitHub Discussions

### ISSUE THREAD

**Issue by zbeyens** [anthropics/claude-code-action#205]
**Describe the bug**
The Claude GitHub App currently doesn't have permissions to respond to GitHub Discussions events, causing "Invalid OIDC token" errors when trying to use @claude mentions in discussion comments.

**To Reproduce**

1. Set up a workflow with discussion and discussion_comment events
2. Create a GitHub Discussion in your repository
3. Add a comment mentioning '@claude' in the discussion
4. See error: "Failed to setup GitHub token: Error: Invalid OIDC token"

**Expected behavior**
Claude should respond to @claude mentions in GitHub Discussions just like it does for issues and pull requests.

**Screenshots**
Error shows: "Failed to setup GitHub token: Error: Invalid OIDC token.

**Workflow yml file**
```yaml
name: Claude

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
```

**Additional context**
The Claude GitHub App currently has these permissions:
- Read access to metadata
- Read and write access to code, issues, and pull requests

But it's missing:
- Read and write access to discussions

This prevents the app from working with GitHub Discussions, which would be a valuable feature for community Q&A, feature discussions, and general support where @claude could provide assistance.

The workflow includes `discussions: read` permission and the appropriate event triggers, but the underlying GitHub App needs to be updated to include discussions permissions.

**Requested Feature:**
Please add "Discussions: Read & Write" permission to the Claude GitHub App so it can respond to @claude mentions in:
1. Discussion posts (`discussion` event)
2. Discussion comments (`discussion_comment` event)
