### ISSUE TITLE
Commit_files tool is failing

### ISSUE THREAD

**Issue by ibrahima** [anthropics/claude-code-action#29]
Hi! I'm trying out the Claude Code GitHub Action, and we've gotten it to work on some issues, but on one issue, I keep asking it to make a PR and it seems to fail to commit any files and so it can't make the PR. Any idea what might be happening, or what I can do to figure out? Thanks!

In the output I see something like this:

```json
  {
    "type": "assistant",
    "message": {
      "id": "sjkdhsaklhhkjsd",
      "type": "message",
      "role": "assistant",
      "model": "claude-3-7-sonnet-20250219",
      "content": [
        {
          "type": "tool_use",
          "id": "toolu_dhfjkldshfsdh",
          "name": "mcp__github_file_ops__commit_files",
          "input": {
            "files": [
              "path/to/file.ext"
            ],
            "message": "Some message\n\n🤖 Generated with [Claude Code](https://claude.ai/code)\n\nCo-authored-by: Claude <noreply@anthropic.com>"
          }
        }
      ],
      "stop_reason": "tool_use",
      "stop_sequence": null,
      "usage": {
        "input_tokens": 3,
        "cache_creation_input_tokens": 503,
        "cache_read_input_tokens": 84823,
        "output_tokens": 378,
        "service_tier": "standard"
      }
    },
    "session_id": "kxjlhasjkldkashjk"
  },
  {
    "type": "user",
    "message": {
      "role": "user",
      "content": [
        {
          "type": "tool_result",
          "content": "Error calling tool commit_files: undefined",
          "is_error": true,
          "tool_use_id": "toolu_dhfjkldshfsdh"
        }
      ]
    },
    "session_id": "kxjlhasjkldkashjk"
  },
```

**Comment by JoeDupuis** [comment]
I have the same error, `mcp__github_file_ops__delete_files` works, but `mcp__github_file_ops__commit_files` returns the undefined error.

**Comment by TorbenWetter** [comment]
Same here. It seems that the MCP tool is not open source, is it?

**Comment by mempirate** [comment]
Same issue!

**Comment by JoeDupuis** [comment]
Unsure what changed, I got one run that failed to delete instead and adding a file worked and now both work. 🤔

**Comment by emcd** [comment]
After a [successful PR creation](https://github.com/emcd/python-project-common/actions/runs/15262954581/job/42923834607) earlier in the day, I encountered the same error with the `mcp__github_file_ops__commit_files` tool on [another PR creation attempt](https://github.com/emcd/python-project-common/actions/runs/15265508089/job/42930371143). Probably either the prompt or the tool description needs to be improved. Or, else there is some problem with updating multiple files... the successful attempt only committed a single file; the unsuccessful attempt had two files. (Or, maybe the MCP server tool does not handle backend errors gracefully.)

## Unsuccessful Attempt
```jsonl
{
  "type": "assistant",
  "message": {
    "id": "msg_011LyCSeYkvbALMPev5WEdLW",
    "type": "message",
    "role": "assistant",
    "model": "claude-sonnet-4-20250514",
    "content": [
      {
        "type": "tool_use",
        "id": "toolu_01EhzKkgrXBTA98ZEqAtyAxV",
        "name": "mcp__github_file_ops__commit_files",
        "input": {
          "files": [
            ".github/workflows/xrepo--claude.yaml",
            "template/.github/workflows/claude.yaml.jinja"
          ],
          "message": "Github Workflows: Create reusable Claude agent workflow\n\n- Factor out Claude workflow logic into xrepo--claude.yaml for cross-repo use\n- Update template to call reusable workflow with proper versioning\n- Fix allowed_tools formatting from pipe-separated to space-separated \n- Remove unnecessary {% raw %} directives around trigger conditions\n- Add proper inputs/secrets interface for workflow customization\n\nAddresses issue #8 by improving maintainability and consistency across repos.\n\nCo-authored-by: emcd <emcd@users.noreply.github.com>"
        }
      }
    ],
    "stop_reason": "tool_use",
    "stop_sequence": null,
    "usage": {
      "input_tokens": 4,
      "cache_creation_input_tokens": 1932,
      "cache_read_input_tokens": 49809,
      "output_tokens": 238,
      "service_tier": "standard"
    }
  },
  "session_id": "2686732f-d2d4-494b-a4d3-980ed0784d20"
}
{
  "type": "user",
  "message": {
    "role": "user",
    "content": [
      {
        "type": "tool_result",
        "content": "Error calling tool commit_files: undefined",
        "is_error": true,
        "tool_use_id": "toolu_01EhzKkgrXBTA98ZEqAtyAxV"
      }
    ]
  },
  "session_id": "2686732f-d2d4-494b-a4d3-980ed0784d20"
}
```

## Successful Attempt
```jsonl
  {
    "type": "assistant",
    "message": {
      "id": "msg_015waEwb5TzMnvYt3JAUepTm",
      "type": "message",
      "role": "assistant",
      "model": "claude-sonnet-4-20250514",
      "content": [
        {
          "type": "tool_use",
          "id": "toolu_01C8cEsXWLzLBPGRGPBTgCBB",
          "name": "mcp__github_file_ops__commit_files",
          "input": {
            "files": [
              "template/.github/workflows/claude.yaml.jinja"
            ],
            "message": "Github Workflows: Create template from `claude` workflow\n\nAdd Jinja2 template for claude.yaml workflow with proper GitHub Actions\nvariable escaping using {% raw %}...{% endraw %} blocks.\n\nCo-authored-by: emcd <emcd@users.noreply.github.com>"
          }
        }
      ],
      "stop_reason": "tool_use",
      "stop_sequence": null,
      "usage": {
        "input_tokens": 4,
        "cache_creation_input_tokens": 1222,
        "cache_read_input_tokens": 38492,
        "output_tokens": 165,
        "service_tier": "standard"
      }
    },
    "session_id": "d1eca3be-230f-4598-99d2-a4de99635633"
  },
  {
    "type": "user",
    "message": {
      "role": "user",
      "content": [
        {
          "tool_use_id": "toolu_01C8cEsXWLzLBPGRGPBTgCBB",
          "type": "tool_result",
          "content": [
            {
              "type": "text",
              "text": "{\n  \"commit\": {\n    \"sha\": \"ae2b7f9fe760f30f6e217e00f9d7ebfcadfff1d6\",\n    \"message\": \"Github Workflows: Create template from `claude` workflow\\n\\nAdd Jinja2 template for claude.yaml workflow with proper GitHub Actions\\nvariable escaping using {% raw %}...{% endraw %} blocks.\\n\\nCo-authored-by: emcd <emcd@users.noreply.github.com>\",\n    \"author\": \"claude[bot]\",\n    \"date\": \"2025-05-26T22:40:53Z\"\n  },\n  \"files\": [\n    {\n      \"path\": \"template/.github/workflows/claude.yaml.jinja\"\n    }\n  ],\n  \"tree\": {\n    \"sha\": \"c6d6c1b6149355f5e261add21a28067ac9421c06\"\n  }\n}"
            }
          ]
        }
      ]
    },
    "session_id": "d1eca3be-230f-4598-99d2-a4de99635633"
  },
```

**Comment by FabianHertwig** [comment]
I ran into the same issue. Could it be that the commit tool errors out when it tries to commit GitHub action workflow files?

Looks to me like that is what all the issues here and in #26 have in common.

**Comment by MrGossett** [comment]
Same issue here.

```json
{
  "type": "assistant",
  "message": {
    "id": "msg_0167Deq3s72g8kdYWSyPYUZN",
    "type": "message",
    "role": "assistant",
    "model": "claude-sonnet-4-20250514",
    "content": [
      {
        "type": "tool_use",
        "id": "toolu_01M2jeHzA2p1RuPkfGoCiFiG",
        "name": "mcp__github_file_ops__commit_files",
        "input": {
          "files": [
            ".golangci.yml",
            ".github/workflows/ci.yml"
          ],
          "message": "feat: add Go linting pipeline ..."
        }
      }
    ],
    "stop_reason": "tool_use",
    "stop_sequence": null,
    "usage": {
      "input_tokens": 4,
      "cache_creation_input_tokens": 679,
      "cache_read_input_tokens": 44511,
      "output_tokens": 280,
      "service_tier": "standard"
    }
  },
  "session_id": "13675db2-9d20-4918-b601-a02ace830f4c"
}
{
  "type": "user",
  "message": {
    "role": "user",
    "content": [
      {
        "type": "tool_result",
        "content": "Error calling tool commit_files: Failed to create tree: 403 - {\"message\":\"Resource not accessible by integration\",\"documentation_url\":\"https://docs.github.com/rest/git/trees#create-a-tree\",\"status\":\"403\"}",
        "is_error": true,
        "tool_use_id": "toolu_01M2jeHzA2p1RuPkfGoCiFiG"
      }
    ]
  },
  "session_id": "13675db2-9d20-4918-b601-a02ace830f4c"
}
```

The GitHub MCP server seems to be operating okay, but it's getting a 403 with a message "Resource not accessible by integration."

The Claude GitHub App is installed for my repo, with permission to read metadata, and read and write code, issues, and pull requests, for all repos in my org.

My `claude.yaml` looks like this:

```yaml
name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: claude-sonnet-4-20250514
```
