### ISSUE TITLE
Failure after 404

### ISSUE THREAD

**Issue by fitz-vivodyne** [anthropics/claude-code-action#32]
I'm attempting to use the default app with Bedrock:

Workflow:
```
name: Claude Action 

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write 

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude-pr:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <redacted>
          aws-region: us-east-1

      - uses: anthropics/claude-code-action@beta
        with:
          trigger_phrase: "@claude"
          timeout_minutes: "60"
          use_bedrock: "true"
```

Logs after the prompt:

```
Run anthropics/claude-code-base-action@beta
Run actions/setup-node@v4
Found in cache @ /opt/hostedtoolcache/node/18.20.8/x64
Environment details
Run oven-sh/setup-bun@v2
Downloading a new version of Bun: https://bun.sh/download/1.2.11/linux/x64?avx2=true&profile=false
/usr/bin/unzip -o -q /home/runner/work/_temp/0a11781b-50a1-4264-982f-7de5a1d6f6ce.zip
/home/runner/.bun/bin/bun --revision
1.2.11+cb6abd211
Run cd /home/runner/work/_actions/anthropics/claude-code-base-action/beta
bun install v1.2.11 (cb6abd21)

+ @types/bun@1.2.12
+ @types/node@20.17.32
+ prettier@3.5.3
+ typescript@5.8.3
+ @actions/core@1.11.1

13 packages installed [100.00ms]
Run npm install -g @anthropic-ai/claude-code@^1.0.2

added 3 packages in 4s

2 packages are looking for funding
  run `npm fund` for details
Run bun run /home/runner/work/_actions/anthropics/claude-code-base-action/beta/src/index.ts
Prompt file size: 12477 bytes
Running Claude with prompt from file: /tmp/claude-prompts/claude-prompt.txt
{
  "type": "system",
  "subtype": "init",
  "session_id": "c5a2ec1d-addc-4373-8b4d-a58765f868af",
  "tools": [
    "Task",
    "Bash",
    "Glob",
    "Grep",
    "LS",
    "Read",
    "Edit",
    "MultiEdit",
    "Write",
    "NotebookRead",
    "NotebookEdit",
    "TodoRead",
    "TodoWrite",
    "mcp__github_file_ops__commit_files",
    "mcp__github_file_ops__delete_files",
    "mcp__github__add_issue_comment",
    "mcp__github__add_pull_request_review_comment",
    "mcp__github__create_branch",
    "mcp__github__create_issue",
    "mcp__github__create_or_update_file",
    "mcp__github__create_pull_request",
    "mcp__github__create_pull_request_review",
    "mcp__github__create_repository",
    "mcp__github__delete_file",
    "mcp__github__fork_repository",
    "mcp__github__get_code_scanning_alert",
    "mcp__github__get_commit",
    "mcp__github__get_file_contents",
    "mcp__github__get_issue",
    "mcp__github__get_issue_comments",
    "mcp__github__get_me",
    "mcp__github__get_pull_request",
    "mcp__github__get_pull_request_comments",
    "mcp__github__get_pull_request_files",
    "mcp__github__get_pull_request_reviews",
    "mcp__github__get_pull_request_status",
    "mcp__github__get_secret_scanning_alert",
    "mcp__github__get_tag",
    "mcp__github__list_branches",
    "mcp__github__list_code_scanning_alerts",
    "mcp__github__list_commits",
    "mcp__github__list_issues",
    "mcp__github__list_pull_requests",
    "mcp__github__list_secret_scanning_alerts",
    "mcp__github__list_tags",
    "mcp__github__merge_pull_request",
    "mcp__github__push_files",
    "mcp__github__search_code",
    "mcp__github__search_issues",
    "mcp__github__search_repositories",
    "mcp__github__search_users",
    "mcp__github__update_issue",
    "mcp__github__update_issue_comment",
    "mcp__github__update_pull_request",
    "mcp__github__update_pull_request_branch",
    "mcp__github__update_pull_request_comment"
  ],
  "mcp_servers": [
    {
      "name": "github_file_ops",
      "status": "connected"
    },
    {
      "name": "github",
      "status": "connected"
    }
  ]
}
{
  "type": "assistant",
  "message": {
    "id": "97806339-ca7f-4a64-b720-55a9fb82c526",
    "model": "<synthetic>",
    "role": "assistant",
    "stop_reason": "stop_sequence",
    "stop_sequence": "",
    "type": "message",
    "usage": {
      "input_tokens": 0,
      "output_tokens": 0,
      "cache_creation_input_tokens": 0,
      "cache_read_input_tokens": 0,
      "server_tool_use": {
        "web_search_requests": 0
      }
    },
    "content": [
      {
        "type": "text",
        "text": "API Error: [404](https://github.com/<org>/<repo>/actions/runs/<run-id>/job/<job-id>#step:4:412) {\"type\":\"error\",\"error\":{\"type\":\"not_found_error\",\"message\":\"Not Found\"}}"
      }
    ]
  },
  "session_id": "c5a2ec1d-addc-4373-8b4d-a58765f868af"
}
{
  "type": "result",
  "subtype": "success",
  "cost_usd": 0,
  "is_error": true,
  "duration_ms": 386,
  "duration_api_ms": 0,
  "num_turns": 1,
  "result": "API Error: 404 {\"type\":\"error\",\"error\":{\"type\":\"not_found_error\",\"message\":\"Not Found\"}}",
  "total_cost": 0,
  "session_id": "c5a2ec1d-addc-[437](https://github.com/<org>/<repo>/actions/runs/<id>/job/<id>#step:4:446)3-8b4d-a58765f868af"
}
Error: Process completed with exit code 1.
Run bun run /home/runner/work/_actions/anthropics/claude-code-action/beta/src/entrypoints/update-comment-link.ts
Fetching issue comment 2902993388
Successfully fetched as issue comment
Branch claude/issue-43-20250523_011528 has no commits from Claude, will delete it
✅ Deleted empty branch: claude/issue-43-20250523_011[528](https://github.com/<org>/<repo>/actions/runs/<id>/job/<id>#step:4:539)
✅ Updated issue comment 2902993388 with job link
Run curl -L \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
