### ISSUE TITLE
Feature: Update PR comments rather than continuously adding

### ISSUE THREAD

**Issue by ruchernchong** [anthropics/claude-code-action#37]
The current implementation caused Claude bot to keep adding more comments to the PR rather than editing the original comment if there is already one. This resulted in a very long PR page. 

The proposed implementation is to edit the comment that the Claude bot has already created.

**Comment by swarajban** [comment]
+1

**Comment by ashwin-ant** [comment]
Can you clarify what you mean here? The current behavior is set up to have Claude edit its own comment in place. What do you expect to be different?

**Comment by robert-dean** [comment]
We setup a PR summarizer workflow and it also adds rather than updating the original comment. Here's our simple workflow:
```yaml
name: Pull Request Summary
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Check out the code to allow git diff operations
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for accurate diffs

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@main
        with:
          # Define the review focus areas
          direct_prompt: 'Summarize the changes in this pull request. Focus on the most important changes and the impact of the changes.'
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: '5'

```
**Note** we're using `@main` instead of `@beta` if that makes a difference

**Comment by jazmine-payscore** [comment]
We are seeing the same issue (but using `@beta`, not `@main`). The documentation says that Claude updates it's own comments but that has not been the case, it adds a new comment every time. Would love to know how to get it to update the original comment instead if that's possible.

**Comment by Shinyaigeek** [comment]
> Can you clarify what you mean here? The current behavior is set up to have Claude edit its own comment in place. What do you expect to be different?

In our usecase, we let claude-code-actions to comment PR's feedback and walkthrough, and we invoke it's workflow when PR is opend and syncronized(=pushed new commit).

In our case, claude-code-actions will create new comment on each `syncronized`, and this behavior causes too many comments and a bit noisy...

Perhaps, I need some parameter to let claude-code-actions to handle it's job with the existing comment instead of creating new comment.

**Comment by ericmatte** [comment]
While waiting for a fix, I've added a simple job that run before Claude to remove old comments:

```yml
jobs:
  delete-old-claude-comments:
    # Currently, the claude-code-action does not support updating its own comments.
    # https://github.com/anthropics/claude-code-action/issues/37
    name: Delete old Claude comments
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Clean up old comments
        uses: actions/github-script@v7
        with:
          script: |
            const params = { issue_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo }
            const comments = await github.rest.issues.listComments(params);

            for (const comment of comments.data) {
              if (comment.user.login === 'claude[bot]') {
                await github.rest.issues.deleteComment({ ...params, comment_id: comment.id });
              }
            }

  claude-review:
    needs: delete-old-claude-comments
    name: Run anthropics/claude-code-action@beta
    # ...
```
