### ISSUE TITLE
Unable To Set Up GitHub Action

### ISSUE THREAD

**Issue by xanderdunn** [anthropics/claude-code-action#40]
Unfortunately I haven't been able to get the Claude Code Action working in GitHub CI either via the `claude` CLI `/install-github-app`, nor via manual configuration. We have a GitHub Enterprise account, but we are not using a custom Claude Code setup, we are directly using the Anthropic API. We're successfully using other GitHub apps, including GitHub Copilot, Google Labs Jules, ChatGPT Connector, etc. 

When I run the `/install-github-app` command, I see:
<img width="860" alt="Image" src="https://github.com/user-attachments/assets/e0e24b4d-af11-42da-987d-99e5915253d6" />
I am signed into GitHub as an admin user. 

The GitHub App is correctly installed:
<img width="966" alt="Image" src="https://github.com/user-attachments/assets/57a2a4ae-a9f4-4862-8ee2-88ff71f88017" />

And the API secret is set on the repo:
<img width="805" alt="Image" src="https://github.com/user-attachments/assets/03994f91-555e-457b-b0cf-ac016cfb40e7" />

So, I tried to set this up manually with `.github/workflows/claude_pr_review.yml`:
```
# This should automatically start a code review when any PR is opened
name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]  # Runs on new PRs and updates

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # Check out the code to allow git diff operations
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffs

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        with:
          # Define the review focus areas
          prompt: "Review the PR changes. Focus on code quality, potential bugs, performance issues, typos, and outdated docs or code. Suggest improvements where appropriate."

          # Limited tools for safer review operations
          allowed_tools: [
            "Bash(git diff --name-only HEAD~1)",  # List changed files
            "Bash(git diff HEAD~1)",              # See actual changes
            "View",                               # Read file contents
            "GlobTool",                          # Find related files
            "GrepTool"                           # Search for patterns
          ]

          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
```
I authorized the workflow, and then it fails:
<img width="658" alt="Image" src="https://github.com/user-attachments/assets/6c0d0b68-2fa6-401f-adce-7ac06975fc57" />
