### ISSUE TITLE
Getting `API Error: 404` when `use_bedrock: "true"`

### ISSUE THREAD

**Issue by mikeparisstuff** [anthropics/claude-code-action#42]
Hey team, great work on Claude! You guys are legends.

I've been pushing through a number of issues getting the Claude code GitHub action setup for automatic code reviews. I'm using bedrock and am trying to understand if I'm misconfiguring something, or perhaps, if there is a bug.

This is my workflow configuration:

```
name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]  # Runs on new PRs and updates

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      # Check out the code to allow git diff operations
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffs

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Test Inference Profile
        run: |
          aws bedrock list-foundation-models --region us-east-2

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        env:
          AWS_REGION: us-east-2
          CLAUDE_CODE_USE_BEDROCK: 1. # i've tried w/ and w/o this
        with:
          github_token: "${{ steps.app-token.outputs.token }}"
          # Define the review focus areas
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed

            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.

          use_bedrock: "true"
          model: "anthropic.claude-sonnet-4-20250514-v1:0"

          # Limited tools for safer review operations
          allowed_tools: "Bash(git status),Bash(git log),Bash(git show),Bash(git blame),Bash(git reflog),Bash(git stash list),Bash(git ls-files),Bash(git branch),Bash(git tag),Bash(git diff),View,GlobTool,GrepTool,BatchTool"
```

It's so very close to working now. I've verified that connectivity to AWS is working via the "Test Inference Profile" step that I added which is working successfully. The role has the correct permissions and the secrets in github actions exist. I almost suspect that the action is just ignoring the `use_bedrock` part of this and is trying to hit the claude public API instead of the bedrock API.

Anyone have any ideas what is wrong?

See error below:

```
Running Claude with prompt from file: /tmp/claude-prompts/claude-prompt.txt
{
  "type": "system",
  "subtype": "init",
  "session_id": "5a8519eb-0bd5-47c7-957f-41d52d298235",
  "tools": [
    "Task",
    "Bash",
    "Glob",
    "Grep",
    "LS",
    "Read",
    "Edit",
    "MultiEdit",
    "Write",
    "NotebookRead",
    "NotebookEdit",
    "TodoRead",
    "TodoWrite",
    "mcp__github_file_ops__commit_files",
    "mcp__github_file_ops__delete_files",
    "mcp__github__add_issue_comment",
    "mcp__github__add_pull_request_review_comment",
    "mcp__github__create_branch",
    "mcp__github__create_issue",
    "mcp__github__create_or_update_file",
    "mcp__github__create_pull_request",
    "mcp__github__create_pull_request_review",
    "mcp__github__create_repository",
    "mcp__github__delete_file",
    "mcp__github__fork_repository",
    "mcp__github__get_code_scanning_alert",
    "mcp__github__get_commit",
    "mcp__github__get_file_contents",
    "mcp__github__get_issue",
    "mcp__github__get_issue_comments",
    "mcp__github__get_me",
    "mcp__github__get_pull_request",
    "mcp__github__get_pull_request_comments",
    "mcp__github__get_pull_request_files",
    "mcp__github__get_pull_request_reviews",
    "mcp__github__get_pull_request_status",
    "mcp__github__get_secret_scanning_alert",
    "mcp__github__get_tag",
    "mcp__github__list_branches",
    "mcp__github__list_code_scanning_alerts",
    "mcp__github__list_commits",
    "mcp__github__list_issues",
    "mcp__github__list_pull_requests",
    "mcp__github__list_secret_scanning_alerts",
    "mcp__github__list_tags",
    "mcp__github__merge_pull_request",
    "mcp__github__push_files",
    "mcp__github__search_code",
    "mcp__github__search_issues",
    "mcp__github__search_repositories",
    "mcp__github__search_users",
    "mcp__github__update_issue",
    "mcp__github__update_issue_comment",
    "mcp__github__update_pull_request",
    "mcp__github__update_pull_request_branch",
    "mcp__github__update_pull_request_comment"
  ],
  "mcp_servers": [
    {
      "name": "github_file_ops",
      "status": "connected"
    },
    {
      "name": "github",
      "status": "connected"
    }
  ]
}
{
  "type": "assistant",
  "message": {
    "id": "93ab[640](https://github.com/my-org/my-repo/actions/runs/15220628098/job/42815463936#step:6:651)2-8e52-4d00-ad93-33bcfafde529",
    "model": "<synthetic>",
    "role": "assistant",
    "stop_reason": "stop_sequence",
    "stop_sequence": "",
    "type": "message",
    "usage": {
      "input_tokens": 0,
      "output_tokens": 0,
      "cache_creation_input_tokens": 0,
      "cache_read_input_tokens": 0,
      "server_tool_use": {
        "web_search_requests": 0
      }
    },
    "content": [
      {
        "type": "text",
        "text": "API Error: 404 {\"type\":\"error\",\"error\":{\"type\":\"not_found_error\",\"message\":\"Not Found\"}}"
      }
    ]
  },
  "session_id": "5a8519eb-0bd5-47c7-957f-41d52d298235"
}
{
  "type": "result",
  "subtype": "success",
  "cost_usd": 0,
  "is_error": true,
  "duration_ms": 289,
  "duration_api_ms": 0,
  "num_turns": 1,
  "result": "API Error: 404 {\"type\":\"error\",\"error\":{\"type\":\"not_found_error\",\"message\":\"Not Found\"}}",
  "total_cost": 0,
  "session_id": "5a8519eb-0bd5-47c7-957f-41d52d298235"
}
Error: Process completed with exit code 1.
```

P.S. I'd recommend updating the public docs at `https://docs.anthropic.com/en/docs/claude-code/github-actions#aws-bedrock-workflow` to mention these points:

1. If you create your own Github App, you need to set `github_token: "${{ steps.app-token.outputs.token }}"` where `app-token` is the `id` of the `uses: actions/create-github-app-token@v2` action.
2. There is no `prompt` parameter, it is `direct_prompt`.
3. `allowed_tools` should be a comma separated list, not a YAML list.
