### ISSUE TITLE
Getting `API Error: 404` when trying to use bedrock

### ISSUE THREAD

**Issue by mikeparisstuff** [anthropics/claude-code-action#43]
Hey team, great work on Claude! You guys are legends.

I've been pushing through a number of issues getting the Claude code GitHub action setup for automatic code reviews. I'm using bedrock and am trying to understand if I'm misconfiguring something, or perhaps, if there is a bug.

This is my workflow configuration:

```
name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]  # Runs on new PRs and updates

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      # Check out the code to allow git diff operations
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffs

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Test Inference Profile
        run: |
          aws bedrock-runtime invoke-model \
            --region us-east-2 \
            --model-id "us.anthropic.claude-sonnet-4-20250514-v1:0" \
            --content-type "application/json" \
            --accept "application/json" \
            --body '{
              "messages": [
                {
                  "role": "user", 
                  "content": "Hello, can you help me review some code?"
                }
              ],
              "max_tokens": 1000,
              "anthropic_version": "bedrock-2023-05-31"
            }' \
            --cli-binary-format raw-in-base64-out \
            response.json
          
          # Then view the response
          cat response.json

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        env:
          AWS_REGION: us-east-2
          CLAUDE_CODE_USE_BEDROCK: 1
          ANTHROPIC_MODEL: "us.anthropic.claude-sonnet-4-20250514-v1:0"
        with:
          github_token: "${{ steps.app-token.outputs.token }}"
          # Define the review focus areas
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed

            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.

          use_bedrock: "true"
          model: "us.anthropic.claude-sonnet-4-20250514-v1:0"

          # Limited tools for safer review operations
          allowed_tools: "Bash(git status),Bash(git log),Bash(git show),Bash(git blame),Bash(git reflog),Bash(git stash list),Bash(git ls-files),Bash(git branch),Bash(git tag),Bash(git diff),View,GlobTool,GrepTool,BatchTool"
```

Unfortunately, no matter what I try, I'm getting this error:

```
Running Claude with prompt from file: /tmp/claude-prompts/claude-prompt.txt
{
  "type": "system",
  "subtype": "init",
  "session_id": "cf36f9a0-4453-4c7e-bab8-1d62ea2b38a2",
  "tools": [
    "Task",
    "Bash",
    "Glob",
    "Grep",
    "LS",
    "Read",
    "Edit",
    "MultiEdit",
    "Write",
    "NotebookRead",
    "NotebookEdit",
    "TodoRead",
    "TodoWrite",
    "mcp__github_file_ops__commit_files",
    "mcp__github_file_ops__delete_files",
    "mcp__github__add_issue_comment",
    "mcp__github__add_pull_request_review_comment",
    "mcp__github__create_branch",
    "mcp__github__create_issue",
    "mcp__github__create_or_update_file",
    "mcp__github__create_pull_request",
    "mcp__github__create_pull_request_review",
    "mcp__github__create_repository",
    "mcp__github__delete_file",
    "mcp__github__fork_repository",
    "mcp__github__get_code_scanning_alert",
    "mcp__github__get_commit",
    "mcp__github__get_file_contents",
    "mcp__github__get_issue",
    "mcp__github__get_issue_comments",
    "mcp__github__get_me",
    "mcp__github__get_pull_request",
    "mcp__github__get_pull_request_comments",
    "mcp__github__get_pull_request_files",
    "mcp__github__get_pull_request_reviews",
    "mcp__github__get_pull_request_status",
    "mcp__github__get_secret_scanning_alert",
    "mcp__github__get_tag",
    "mcp__github__list_branches",
    "mcp__github__list_code_scanning_alerts",
    "mcp__github__list_commits",
    "mcp__github__list_issues",
    "mcp__github__list_pull_requests",
    "mcp__github__list_secret_scanning_alerts",
    "mcp__github__list_tags",
    "mcp__github__merge_pull_request",
    "mcp__github__push_files",
    "mcp__github__search_code",
    "mcp__github__search_issues",
    "mcp__github__search_repositories",
    "mcp__github__search_users",
    "mcp__github__update_issue",
    "mcp__github__update_issue_comment",
    "mcp__github__update_pull_request",
    "mcp__github__update_pull_request_branch",
    "mcp__github__update_pull_request_comment"
  ],
  "mcp_servers": [
    {
      "name": "github_file_ops",
      "status": "connected"
    },
    {
      "name": "github",
      "status": "connected"
    }
  ]
}
{
  "type": "assistant",
  "message": {
    "id": "6a01fc68-a0d6-4292-bc5a-f537a852[704](https://github.com/Brace-Health/bracehealth/actions/runs/15220948808/job/42816305533#step:6:715)b",
    "model": "<synthetic>",
    "role": "assistant",
    "stop_reason": "stop_sequence",
    "stop_sequence": "",
    "type": "message",
    "usage": {
      "input_tokens": 0,
      "output_tokens": 0,
      "cache_creation_input_tokens": 0,
      "cache_read_input_tokens": 0,
      "server_tool_use": {
        "web_search_requests": 0
      }
    },
    "content": [
      {
        "type": "text",
        "text": "API Error: 404 {\"type\":\"error\",\"error\":{\"type\":\"not_found_error\",\"message\":\"Not Found\"}}"
      }
    ]
  },
  "session_id": "cf36f9a0-4453-4c7e-bab8-1d62ea2b38a2"
}
{
  "type": "result",
  "subtype": "success",
  "cost_usd": 0,
  "is_error": true,
  "duration_ms": 562,
  "duration_api_ms": 0,
  "num_turns": 1,
  "result": "API Error: 404 {\"type\":\"error\",\"error\":{\"type\":\"not_found_error\",\"message\":\"Not Found\"}}",
  "total_cost": 0,
  "session_id": "cf36f9a0-4453-4c7e-bab8-1d62ea2b38a2"
}
Error: Process completed with exit code 1.
```

My role is setup, I have model access in bedrock, I have set all the relevant secrets in github actions. I added a test step to try to verify AWS connectivity and I've verified access to bedrock works from that step.

I suspect that claude code is just ignoring the `use_bedrock` parameter (as well as the env variables that I tried to set from normal claude code) and is instead trying to use the public anthropic API instead of bedrock.

Any ideas?

**Comment by mikeparisstuff** [comment]
@claude, do you know?

**Comment by mikeparisstuff** [comment]
Update. I set the `ANTHROPIC_BEDROCK_BASE_URL` env variable and it seems to be trying to do work now. Progress!

```
ANTHROPIC_BEDROCK_BASE_URL: "https://bedrock-runtime.us-east-2.amazonaws.com"
```

Unfortunately I got throttled by bedrock and now see this error:

```
API Error: 429 Too many tokens, please wait before trying again.
```

I then downgraded to claude 3.7 because I have higher limits on bedrock and things seem to be working now. I'll leave this issue open in case it's helpful for someone else. Otherwise feel free to close it.

**Comment by fitz-vivodyne** [comment]
Confirmed that this solved 404 issues for me as well in #32.
Here is my full working workflow:

```
name: Claude Action 

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write 

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<redacted>:role/<redacted>
          aws-region: us-east-1

      - uses: anthropics/claude-code-action@beta
        with:
          trigger_phrase: "@claude"
          timeout_minutes: "60"
          use_bedrock: "true"
        env:
          ANTHROPIC_BEDROCK_BASE_URL: "https://bedrock-runtime.us-east-1.amazonaws.com"

```
