### ISSUE TITLE
Error calling tool update_issue_comment: undefined

### ISSUE THREAD

**Issue by mikeparisstuff** [anthropics/claude-code-action#45]
# Issue

After what otherwise looks like a successful run, I see this error when its trying to write its results back to the pull request:

```
{
    "type": "user",
    "message": {
      "role": "user",
      "content": [
        {
          "type": "tool_result",
          "content": "Error calling tool update_issue_comment: undefined",
          "is_error": true,
          "tool_use_id": "toolu_bdrk_01U8nrvfSoSyJeuML6aCiAt2"
        }
      ]
    },
    "session_id": "1a9fa5d5-7fb5-4401-97fe-7cc77adb353c"
  }
```

This is my workflow

```
name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]  # Runs on new PRs and updates

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      # Check out the code to allow git diff operations
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffs

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        env:
          AWS_REGION: us-east-2
          ANTHROPIC_BEDROCK_BASE_URL: "https://bedrock-runtime.us-east-2.amazonaws.com"
        with:
          github_token: "${{ steps.app-token.outputs.token }}"
          # Define the review focus areas
          direct_prompt: |
            Please review this PR. Look at the changes and provide thoughtful feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Suggestions for improvements
            - Overall architecture and design decisions
            
            Be constructive and specific in your feedback. Give inline comments where applicable.

          use_bedrock: "true"
          model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
```

And the app has read/write to content, issues, and pull requests. I don't have any `allowed_tools` or `not_allowed_tools` set in my workflow config with the intention of just taking the defaults as I've found the documentation to be a bit unreliable.

# Expected Behavior

I'd expect this tool call to work given the permissions that this workflow has.

Any ideas what is wrong?
