### ISSUE TITLE
Cannot specify Node.js version in Claude Code environment

### ISSUE THREAD

**Issue by TakuSemba** [anthropics/claude-code-action#56]
## Issue

When using the following GitHub Action, the `Display Node.js and Yarn versions` step shows Node.js version as v20.18.0, but in the `Run Claude PR Action` step, when Claude Code executes the same `node --version` command, it returns v18.20.8.

I would like to set up a specific version of Node.js in Claude Code's execution environment.

### Reproducible Github Action

```yaml
name: Claude PR Assistant

on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]

env:
  CI_NODE_VERSION: 20.18.0

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CI_NODE_VERSION }}
          cache: "yarn"

      - name: Display Node.js and Yarn versions
        run: |
          echo "Node.js version: $(node --version)"
          echo "Yarn version: $(yarn --version)"

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          allowed_tools: Bash
```

### Output Log

<img src="https://github.com/user-attachments/assets/b7cbb97b-e6bf-46bc-ac25-449f64a4d222" width="600">

```
Run echo "Node.js version: $(node --version)"
  echo "Node.js version: $(node --version)"
  echo "Yarn version: $(yarn --version)"
  shell: /usr/bin/bash -e {0}
  env:
    CI_NODE_VERSION: [2](https://github.com/TakuSemba/sample-claude-code-github-action/actions/runs/15252273459/job/42891698024#step:4:2)0.18.0
Node.js version: v20.18.0  // <---- it shows "v20.18.0"
Yarn version: 1.22.22

...

{
  "type": "assistant",
  "message": {
    "id": "msg_01RTJvniBChvVEdfoxivFayf",
    "type": "message",
    "role": "assistant",
    "model": "claude-sonnet-4-20250514",
    "content": [
      {
        "type": "tool_use",
        "id": "toolu_01BcGCJcNpzX7uKvEicJvLEW",
        "name": "Bash",
        "input": {
          "command": "node --version",
          "description": "Check Node.js version"
        }
      }
    ],
    "stop_reason": "tool_use",
    "stop_sequence": null,
    "usage": {
      "input_tokens": 6,
      "cache_creation_input_tokens": 3049,
      "cache_read_input_tokens": 23948,
      "output_tokens": 95,
      "service_tier": "standard"
    }
  },
  "session_id": "3370ae8f-585a-4907-8447-bf2330250b1f"
}
{
  "type": "user",
  "message": {
    "role": "user",
    "content": [
      {
        "tool_use_id": "toolu_01BcGCJcNpzX7uKvEicJvLEW",
        "type": "tool_result",
        "content": "v18.20.8", // <---- it shows "v18.20.8"
        "is_error": false
      }
    ]
  },
  "session_id": "3370ae8f-585a-4907-8447-bf2330250b1f"
}
```
