### ISSUE TITLE
Claude Code Action on Self-Hosted Runner

### ISSUE THREAD

**Issue by simonbucher** [anthropics/claude-code-action#57]
Hi,

I'd like to run the Claude Code GitHub Action workflow on my self-hosted macOS runner. Currently, the workflow triggers,  and everything is green and successful in the workflow execution, but it doesn't post comments on issues.

How can I make the Claude Code action comment on issues when running on a self-hosted runner?

<img width="1054" alt="Image" src="https://github.com/user-attachments/assets/da85ad66-a15f-4c0f-90fe-b7290bf76f22" />

Here is my workflow:

```
name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: [self-hosted, macOS]
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.CLAUDE_GITHUB_TOKEN }}
```
