### ISSUE TITLE
Inline comments for reviews

### ISSUE THREAD

**Issue by AwolDes** [anthropics/claude-code-action#60]
Instead of a block comment, if Claude identifies a particular piece of code it would be more readable if it added in line comments.

An example from our custom Claude Code review action:
---

![Image](https://github.com/user-attachments/assets/3dd8cb48-409a-44b3-9933-e3b4713ba9f0)

An example from the Anthropic Claude Code github action:
---

![Image](https://github.com/user-attachments/assets/3069f2d9-9972-44bf-bb26-cb93946b6b76)

With a comment like this, it'd be better left as a `suggestion` block around the specific piece of code

**Comment by Phoenixmatrix** [comment]
It can and will do inline comments. You just need to enable the tools in allowed_tools, and make sure the instructions it uses in the github actions tell it to do so.

**Comment by sepehr500** [comment]
@Phoenixmatrix I can not get this to work. Adding ` allowed_tools: "mcp__github__add_pull_request_review_comment"` and being explicit to only leave in-line comments does nothing. It does not seem to have access to this tool. How are you making it work?

**Comment by sepehr500** [comment]
@AwolDes I figured it out. Turns out the example in the claude-code-action repo is out of date. Here is a yml snippet that worked for me.

I also made a PR to fix the docs in this repo https://github.com/anthropics/claude-code-action/pull/145


```        with:
          direct_prompt: |
            Please review this PR and provide inline feedback using the GitHub review system. Follow these steps:

            1. **Start a review**: Use `mcp__github__create_pending_pull_request_review` to begin a pending review
            2. **Get diff information**: Use `mcp__github__get_pull_request_diff` to understand the code changes and line numbers
            3. **Add inline comments**: Use `mcp__github__add_pull_request_review_comment_to_pending_review` for each specific piece of feedback on particular lines
            4. **Submit the review**: Use `mcp__github__submit_pending_pull_request_review` with event type "COMMENT" (not "REQUEST_CHANGES") to publish all comments as a non-blocking review

            Focus your review on:
            - Code quality and best practices
            - Potential bugs or security issues
            - Performance considerations
            - Maintainability and readability
            - Architecture and design decisions

            Provide specific, actionable feedback. Use inline comments for line-specific issues and include an overall summary when submitting the review. **Important**: Submit as "COMMENT" type so the review doesn't block the PR.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: "mcp__github__create_pending_pull_request_review,mcp__github__add_pull_request_review_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github__get_pull_request_diff"
```

**Comment by AwolDes** [comment]
@sepehr500 thanks for this! It's now working in our repo

**Comment by saada** [comment]
It's working now but super noisy and chatty. Any tips?

**Comment by cristopherfreitas** [comment]
For me it doesn't work properly yet. Did something change recently that broke this?

**Comment by cristopherfreitas** [comment]
Okay, I finally figured. The actual example from the workflow is broken. It's using `--allowed-tools` instead of `--allowedTools` when passing to `claudeArgs`.

**Comment by ashwin-ant** [comment]
> It's using --allowed-tools instead of --allowedTools when passing to claudeArgs.

Did this actually fix it? Both should work just fine.

**Comment by ashwin-ant** [comment]
Ah actually we had a bug here: https://github.com/anthropics/claude-code-action/pull/581. So kebab case will soon work.

**Comment by WendaoLee** [comment]
Does anyone know what's the exact workflow file  example? For the #145 , I saw the example code were:

```yml
      - name: Automatic PR Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.
            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed
            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.
          # allowed_tools: "mcp__github__add_pull_request_review_comment"
          # allowed_tools: "mcp__github__create_pending_pull_request_review,mcp__github__add_pull_request_review_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github__get_pull_request_diff"
```

But when I ran this CI, I just got:
```
Unexpected input(s) 'direct_prompt', 'allowed_tools', valid inputs are ['trigger_phrase', 'assignee_trigger', 'label_trigger', 'base_branch', 'branch_prefix', 'allowed_bots', 'allowed_non_write_users', 'prompt', 'settings', 'anthropic_api_key', 'claude_code_oauth_token', 'github_token', 'use_bedrock', 'use_vertex', 'claude_args', 'additional_permissions', 'use_sticky_comment', 'use_commit_signing', 'bot_id', 'bot_name', 'track_progress', 'experimental_allowed_domains', 'path_to_claude_code_executable', 'path_to_bun_executable']
```

What should I do to enable inline comments?😭

**Comment by WendaoLee** [comment]
> I was not able to make the bot post inline comments.
> 
> The mcp servers are not being enabled for me even when I add `mcp__github_inline_comment__create_inline_comment` to the list of allowed tools. Not sure what's going on there.

Hi, I discovered the reason yesterday: many GitHub MCP tools have undergone name changes (e.g., see [this pull request](https://github.com/github/github-mcp-server/pull/697)). Due to these changes being somewhat under the radar, I couldn't compile a clear list of them.

Here is my final solution workflow file for reference (the prompt is Chinese,you can translate it into yourself):

```yml
name: Code Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            请审查这个 PR 并使用 GitHub 审查系统提供内联反馈。请按照以下步骤操作：
            1.开始审查：使用 mcp__github__create_pending_pull_request_review 开始一个待处理的审查
            2.获取差异信息：使用 mcp__github__get_pull_request_diff 了解代码变更和行号。请注意，如果 pull request 的更改量过多，记得做好分页获取。
            3.添加内联评论：使用 mcp__github__add_comment_to_pending_review 对特定行的具体代码片段提供反馈
            4.提交审查：使用 mcp__github__submit_pending_pull_request_review 并设置事件类型为 "COMMENT"（不是 "REQUEST_CHANGES"）来发布所有评论作为非阻塞性审查
            请重点关注一下方面：
            - 这段修改是否存在潜在的 bug 或安全问题
            - 这段修改是否存在令人无法理解的逻辑
            - 是否存在潜在的性能隐患

            永远使用内联评论进行有问题的代码片段的评论。添加内联评论应该使用 mcp__github__add_comment_to_pending_review 这个工具。
            永远使用中文回复。

            关于这个项目的其他基础信息：
            - Owner: ${{ github.repository_owner }}
            - Repository: ${{ github.repository }}
            - Pull Request: ${{ github.event.pull_request.number }}
            - Pull Request Title: ${{ github.event.pull_request.title }}
            - Pull Request Body: ${{ github.event.pull_request.body }}
            - Pull Request Created At: ${{ github.event.pull_request.created_at }}
            - Pull Request Updated At: ${{ github.event.pull_request.updated_at }}
            - Pull Request Diff Url: ${{ github.event.pull_request.diff_url }}

          claude_args: |
            --allowedTools "mcp__github__get_pull_request,mcp__github__create_pending_pull_request_review,mcp__github__add_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github__get_pull_request_diff"

        env:
            MAX_MCP_OUTPUT_TOKENS: "50000"
```

**Comment by yteruel31** [comment]
If I set `use_sticky_comment` as `true`, does this property include inline comments as well? Or do I need to leave to `false`?

**Comment by vmohir** [comment]
None of the above worked for me with v1. This works:

```yml
- name: Run Claude PR Action
  id: claude
  uses: anthropics/claude-code-action@v1
  with:
    anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
    track_progress: true
    prompt: |
      When reviewing pull requests, follow these steps:
      1. Start a review
      2. For each issue / nitpick / question that points at specific lines, add an inline comment with. Prefix comments with `issue:`|`nitpick:`|`question:`. Use ```suggestion``` blocks for code change suggestions.
      3. Replace the tracking comment using the template below. any feedback not specific to a line goes here
      4. Publish the review as non-blocking (comment)

      Template for the general review comment:
      ${{ steps.template.outputs.content }}
    # language=sh
    claude_args: |
      --allowedTools "Bash(dotnet run),Bash(dotnet test:*),Bash(dotnet csharpier:*),Bash(dotnet tool restore),Read,Write,Glob,Grep,Edit,Task,Bash(gh:*),Bash(git:*),Bash(npm run:*),Bash(sed:*),Bash(rg:*),mcp__github__create_pending_pull_request_review,mcp__github__add_pull_request_review_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github__get_pull_request_diff,mcp__github,mcp__github__create_issue_comment,mcp__github_inline_comment,mcp__github_inline_comment__create_inline_comment,mcp__github_comment,mcp__github_comment__update_claude_comment"

```
