### ISSUE TITLE
Claude Code claims it has no access to Bash tool

### ISSUE THREAD

**Issue by chetanpepper** [anthropics/claude-code-action#68]
I am trying to give Claude Code the ability to check out specific git lfs files on demand. I have done this by adding the the `allowed_tools` variable in the workflow file:

```yml
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.claude_github }}
          allowed_tools: "Bash(poetry install),Bash(pre-commit run --all-files --hook-stage=push),Bash(git lfs *)"
```

These are pulled into the `ALLOWED_TOOLS` environment variable in the Github Action

```
ALLOWED_TOOLS: Edit,Glob,Grep,LS,Read,Write,mcp__github_file_ops__commit_files,mcp__github_file_ops__delete_files,mcp__github__update_issue_comment,Bash(poetry install),Bash(pre-commit run --all-files --hook-stage=push),Bash(git lfs *)
```

However, Claude claims that it has no access to Bash and that it cannot run `git lfs checkout`:

```
    "model": "claude-sonnet-4-20250514",
    "content": [
      {
        "type": "text",
        "text": "I notice that I don't have access to the Bash tool, which means I can't run `git lfs checkout` directly. Let me try to use the Task tool to handle this:"
      }
    ],
```

How can I modify the workflow file or otherwise give Claude access to run `git lfs checkout`?
