### ISSUE TITLE
Error during "Exchanging OIDC token for app token..."

### ISSUE THREAD

**Issue by dylangarcia** [anthropics/claude-code-action#8]
I'm using the template workflow as follows:

```
name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
```

When triggering this on a PR, it gets stuck in an auth loop and then eventually errors:

```
Run bun run /home/runner/work/_actions/anthropics/claude-code-action/beta/src/entrypoints/prepare.ts
  
Requesting OIDC token...
Attempt 1 of 3...
OIDC token successfully obtained
Exchanging OIDC token for app token...
Attempt 1 of 3...
Attempt 1 failed: App token exchange failed: 401 Unauthorized
Retrying in 5 seconds...
Attempt 2 of 3...
Attempt 2 failed: App token exchange failed: 401 Unauthorized
Retrying in 10 seconds...
Attempt 3 of 3...
Attempt 3 failed: App token exchange failed: 401 Unauthorized
Error: Failed to setup GitHub token: Error: Operation failed after 3 attempts. Last error: App token exchange failed: 401 Unauthorized
Error: Process completed with exit code 1.
```

Is this something to do with my Github token or is this a bug in the workflow?

Edit: It looks like it's actually a 401 coming from Anthropic, so is it my Anthropic key? 🤔

**Comment by AWoLnik** [comment]
I'm having the same issue.

Were you able to retrieve your claude code key somehow, or did you create a new key in the `Default` workspace? The Anthropic console doesn't seem to let you create new API keys in the `Claude Code` workspace, although I'm not sure if that's relevant.

Edit: FWIW this is my workflow, [which came from the docs + a syntax fix](https://docs.anthropic.com/en/docs/claude-code/github-actions#basic-workflow-setup)

```
name: Claude PR Creation
on:
  issue_comment:
    types: [created]  # Triggers when someone comments on an issue or PR

jobs:
  create-pr:
    # Only run if the comment mentions @claude
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          # Pass the comment text as the prompt
          prompt: "${{ github.event.comment.body }}"

          # Define which tools Claude can use
          allowed_tools: >-
            - "Bash(git status)"
            - "Bash(git log)"
            - "Bash(git show)"
            - "Bash(git blame)"
            - "Bash(git reflog)"
            - "Bash(git stash list)"
            - "Bash(git ls-files)"
            - "Bash(git branch)"
            - "Bash(git tag)"
            - "Bash(git diff)"
            - "View"
            - "GlobTool"
            - "GrepTool"
            - "BatchTool"

          # Your Anthropic API key (stored as a GitHub secret)
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
```

**Comment by ashwin-ant** [comment]
Just to make sure, have you installed the [Claude GitHub app](https://github.com/apps/claude) to your repo? That's needed (if you install via `/install-github-app` from Claude Code it'll walk you through this).

**Comment by Aayush9029** [comment]
@ashwin-ant 
@claude
running into the same issue.

I've installed Claude Code app on all of my repos, added ANTHROPIC_APIKEY on the repo I'm testing

- initially ran into "Resource not accessible by integration" [FULL LOG](https://productionresultssa17.blob.core.windows.net/actions-results/424eeeb9-76a4-4b7a-a6a1-594f8fd0035b/workflow-job-run-c61cfa41-c224-5bc6-6517-1cea2d118937/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-05-20T04%3A42%3A22Z&sig=Aw%2FoKHiADNrgpZ487o07nnA1uxFb6hdHmmqnaJL7HFE%3D&ske=2025-05-20T13%3A52%3A04Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-05-20T01%3A52%3A04Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-05-20T04%3A32%3A17Z&sv=2025-05-05)

- then as per work around I removed the secrets.GITHUB_TOKEN #9 from workflow

which then brought up this error [FULL LOG](https://productionresultssa17.blob.core.windows.net/actions-results/424eeeb9-76a4-4b7a-a6a1-594f8fd0035b/workflow-job-run-c61cfa41-c224-5bc6-6517-1cea2d118937/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-05-20T04%3A43%3A17Z&sig=P%2BGH%2F8kd5CFzzZFaKWOpglrZvPewDBo67wLltfxf4d4%3D&ske=2025-05-20T13%3A52%3A17Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-05-20T01%3A52%3A17Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-05-20T04%3A33%3A12Z&sv=2025-05-05)

---

- tried using /install-github-app in the beggning has couple different issues, so had to add manually

1. It doesn't want to use the APIKey (clean flow and re-add flow) (both first time and after adding manually)

![Image](https://github.com/user-attachments/assets/dbc341b8-a969-44d8-9c9b-badda1377536)

2.

```> /install-github-app
  ⎿  Couldn't install GitHub App: gh: Invalid request.

     "sha" wasn't supplied. (HTTP 422)

     For manual setup instructions, see: https://github.com/anthropics/claude-pr-action/#manual-setup-direct-api
```


I can assure you Claude Code has full access via GitHub Settings on the (Website)

gh has all privileges and so does git

![Image](https://github.com/user-attachments/assets/5962fda8-d230-40ce-ad0a-5756e697d083)

**Comment by ashwin-ant** [comment]
@Aayush9029 that error may occur if you already have a `.github/workflows/claude.yml` file in the repo. We'll look into fixing this!

In the meantime, if you have the app installed and key setup, then all you need is a workflow file from our examples and tagging Claude should work.

**Comment by Aayush9029** [comment]
Thanks @ashwin-ant,

Here's a WORKAROUND

using this yaml +

`echo $ANTHROPIC_API_KEY| gh secret set ANTHROPIC_API_KEY -a actions` (or using website)

works!


```yaml
name: Claude

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-pr:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Agent
        uses: anthropics/claude-code-action@main
        with:
          timeout_minutes: "60"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: "Bash(bun install),Bash(bun test:*),Bash(bun run format),Bash(bun typecheck)"
          custom_instructions: "You have also been granted tools for editing files and running bun commands (install, run, test) for testing your changes."
```

**Comment by digi0pz** [comment]
Facing similar issues with our setup. 
Used the same format as the example - but getting this:

```
Requesting OIDC token...
Attempt 1 of 3...
OIDC token successfully obtained
Exchanging OIDC token for app token...
Attempt 1 of 3...
Attempt 1 failed: App token exchange failed: 401 Unauthorized
Retrying in 5 seconds...
Attempt 2 of 3...
Attempt 2 failed: App token exchange failed: 401 Unauthorized
Retrying in 10 seconds...
Attempt 3 of 3...
Attempt 3 failed: App token exchange failed: 401 Unauthorized
Error: Failed to setup GitHub token: Error: Operation failed after 3 attempts. Last error: App token exchange failed: 401 Unauthorized
Error: Process completed with exit code 1.
```

**Comment by AWoLnik** [comment]
@Aayush9029 what do you believe is the workaround here? I tried your workflow in a new repo and it works; it's in the same github org with the same org-wide secret. As far as I can tell, the only meaningful differences between your workflow and @dylangarcia's workflow are that you're using `claude-code-action@main` instead of `claude-code-action@beta` and passing in the `allowed_tools` and `custom_instructions` strings, although I ran it again with those changes reverted and it's still working. Makes me think it's repo configuration issue, and not the workflow.

**Comment by AWoLnik** [comment]
Ah, I noticed @dylangarcia and I had slightly different error messages about the OIDC token. I'm not sure what's causing his 401, but I was actually getting a different error:

`Attempt 1 failed: Failed to get OIDC token: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable`

I was able to resolve this by adding the `id-token: write` permission to the job.

Overall, it seems like the [example workflows provided in the Anthropic docs](https://docs.anthropic.com/en/docs/claude-code/github-actions#basic-workflow-setup) are missing the needed permissions and the checkout step. The [stock example workflow in this repo](https://github.com/anthropics/claude-code-action/blob/main/examples/claude.yml) works well for me out of the box.

**Comment by dylangarcia** [comment]
@AWoLnik I originally had ` Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable` too and had to add the permissions after doing some digging.

**Comment by ashwin-ant** [comment]
Thanks for reporting, we'll get this updated.

**Comment by dylangarcia** [comment]
@ashwin-ant I added the Claude app to the repo and things are working now. Feel free to close this out if needbe!

**Comment by digi0pz** [comment]
Hi @ashwin-ant we are still facing this. 
We have tried adding all permissions and verifying the token.
The Claude app is already connected to the repository.
Is there anything else we can try?

**Comment by ashwin-ant** [comment]
@digi0pz can you paste the exact claude yml file that you're using here?

**Comment by digi0pz** [comment]
Sure, this is the exact actions file we are using:

```
name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: qa-arc-runner-set  // our internal runner
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
```

**Comment by ashwin-ant** [comment]
@digi0pz just as a sanity check, does the person who's doing the Claude tagging have write permissions on the repo? This is required for the OIDC fetch to work.

**Comment by andrewhampton** [comment]
I'm seeing this issue as well, and I think the root cause may be what you mentioned @ashwin-ant. My workflow is:

1. Exception reported to Honeybadger
2. Honeybadger creates a GitHub issue
3. Issue triggers GitHub Action that runs Claude to create a PR with a proposed fix

Know of any workaround for this integration not having write permissions on the repo?

**Comment by jkneal** [comment]
Same error here. App is installed. Here is my workflow file:

```
name: Claude Code Review

on:
  pull_request_target:
    types: [opened, synchronize]  # Runs on new PRs and updates

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed

            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.
```

**Comment by ashwin-ant** [comment]
@jkneal we rolled out an update with some clearer errors in the workflow page. Can you see if it provides more information about your issue?

**Comment by ashwin-ant** [comment]
@andrewhampton we require the user tagging Claude to have write permissions in the repo, since the Claude app has write permissions on the repo, and thus we don't want to grant new permissions to people implicitly.

**Comment by andrewhampton** [comment]
@ashwin-ant that makes sense to me as a safe default. Is this a technical constraint or a security constraint? If it's a security constraint, what do you think about adding an escape hatch so users can opt-in to the less secure behavior?

**Comment by jkneal** [comment]
@ashwin-ant Here is what I see in the workflow logs:

Requesting OIDC token...
Attempt 1 of 3...
OIDC token successfully obtained
Exchanging OIDC token for app token...
Attempt 1 of 3...
App token exchange failed: 401 Unauthorized - Invalid OIDC token
Attempt 1 failed: Invalid OIDC token
Retrying in 5 seconds...
Attempt 2 of 3...
App token exchange failed: 401 Unauthorized - Invalid OIDC token
Attempt 2 failed: Invalid OIDC token
Retrying in 10 seconds...
Attempt 3 of 3...
App token exchange failed: 401 Unauthorized - Invalid OIDC token
Attempt 3 failed: Invalid OIDC token
Operation failed after 3 attempts
Error: Failed to setup GitHub token: Error: Invalid OIDC token.

If you instead wish to use this action with a custom GitHub token or custom GitHub app, provide a `github_token` in the `uses` section of the app in your workflow yml file.
Error: Process completed with exit code 1.
Run curl -L \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   [109](https://github.com/jkneal/rwa/actions/runs/15426785351/job/43415606632#step:3:114)  100   109    0     0   2023      0 --:--:-- --:--:-- --:--:--  2056
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}

**Comment by ashwin-ant** [comment]
> Is this a technical constraint or a security constraint? If it's a security constraint, what do you think about adding an escape hatch so users can opt-in to the less secure behavior?

This is a security constraint to prevent privilege escalation. Tagging Claude is effectively a way to gain write access on a repo that you don't have it on, which is particularly bad for open source repos where anyone can comment on issues.

**Comment by ashwin-ant** [comment]
@jkneal that's really odd. Your workflow file looks right. Is there anything else about your setup that might be unique? We'll look into this.

**Comment by jkneal** [comment]
@ashwin-ant Can't think of anything. This is what I did:

- created a new repo
- added some code
- Installed Claude app
- Set ANTHROPIC_API_KEY secret
- Added workflow above
- Created a PR

**Comment by kentoyoshidatrust** [comment]
I’m experiencing the same issue. I’ve configured Claude Code via the [GitHub App page](https://github.com/apps/claude), supplied the Anthropic API key, and added [the sample workflow file](https://github.com/anthropics/claude-code-action/blob/main/examples/claude.yml).

A few environment details:
- The repository sits in an organization that restricts access by IP address.
- Because of this, the workflow runs on a self-hosted runner rather than `ubuntu-latest`.
- I’ve verified that the GitHub token has read & write permissions in the organization-level.

The log is exactly same as [this comment](https://github.com/anthropics/claude-code-action/issues/8#issuecomment-2937036776).
Could there be any other factors preventing the action from working?

**Comment by miroblog** [comment]
(here is the solution @kentoyoshidatrust ) add the github token manually 
```
with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.MY_CUSTOM_GITHUB_TOKEN }}
```

**Comment by mnapoli** [comment]
I'm getting the error as well, it seems random.

I'm able to tag `@claude` to implement issues or review a PR or implement some changes. But _sometimes_ the error happens. I'm brand new at this so it's still fresh, but it seems to be failing 50% of the time.

- yes I'm an admin user with write permission (only person on the repo)
- yes the GitHub app is installed, has permissions to all repos
- the workflow files are brand new, not customized, all created via the automatic creation process

It _seems_ that the error is happening when I tag claude to fix something in a PR (in the diff): could it be that the commit created by Claude (even though it is attached to me) has less permissions somehow?

<img width="548" height="206" alt="Image" src="https://github.com/user-attachments/assets/ad436ec0-6dfd-4790-89a2-b1151f3a84fd" />

**Comment by kenfdev** [comment]
@mnapoli 
Same here.  

> It seems that the error is happening when I tag claude to fix something in a PR (in the diff): could it be that the commit created by Claude (even though it is attached to me) has less permissions somehow?

According to the docs, I guess bot triggered workflows aren't allowed?

https://github.com/anthropics/claude-code-action?tab=readme-ov-file#access-control

> No Bot Triggers: GitHub Apps and bots cannot trigger this action

Would love some official comments about this.

**Comment by tonglil** [comment]
I have the same issue (and environment) as @kentoyoshidatrust

If I override and switch to GITHUB_TOKEN, it works, but now it no longer uses the Claude GitHub App (as expected):
```yaml
        with:
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

I'm wondering if there is some issue with using non-GitHub runners that prevents the `id-token` from being generated or accepted by Anthropic? Because the error is directly related to the [token exchange happening here](https://github.com/anthropics/claude-code-action/blob/b6868bfc27c5ff8f88a20b52c6b53f4bbe83fa6c/src/github/token.ts#L19-L40).
