### ISSUE TITLE
Claude is not using the  CLOUD_ML_REGION

### ISSUE THREAD

**Issue by daniakaguict** [anthropics/claude-code-action#81]
**Describe the bug**
The `claude-code-action` fails with the error message: “The client should be instantiated with the `region` option or the `CLOUD_ML_REGION` environment variable should be set,” despite the logs indicating that the variable is present

**To Reproduce**
1. Follow the steps defined in https://github.com/anthropics/claude-code-action?tab=readme-ov-file#oidc-authentication-for-bedrock-and-vertex for Vertex AI
2. Create an Issue
3. Add a comment @claude to trigger the workflow

**Expected behavior**
The CLOUD_ML_REGION should be passed to the client

**Screenshots**
N/A

**Workflow yml file**
```
name: Claude Assistant

env:
  ANTHROPIC_VERTEX_PROJECT_ID: "****"
  CLOUD_ML_REGION: "us-east5"

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]



jobs:
  claude-response:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'assigned') && contains(github.event.issue.body, '@claude'))

    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      id-token: write # Required for OIDC

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ****
          service_account: ****
          token_format: access_token

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
            app-id: ${{ vars.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Claude Code Implementation
        uses: anthropics/claude-code-action@beta
        with:
          use_vertex: "true"
          trigger_phrase: "@claude"
          timeout_minutes: 60
          github_token: ${{ steps.app-token.outputs.token }}
          anthropic_model: "claude-3-7-sonnet-20250219"
          allowed_tools: "Bash(make test),Bash(yarn install),Bash(yarn lint),Bash(yarn format),Bash(yarn test),Read,Edit,Write,Grep,Task,Replace"

```

**API Provider**

[ ] Anthropic First-Party API (default)
[ ] AWS Bedrock
[X] GCP Vertex

**Additional context**
Logs:

```
Run bun run /home/runner/work/_actions/anthropics/claude-code-base-action/*****/src/index.ts
  bun run /home/runner/work/_actions/anthropics/claude-code-base-action/*****/src/index.ts
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ANTHROPIC_VERTEX_PROJECT_ID: *****
    CLOUD_ML_REGION: us-east5
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: *****.json
    GOOGLE_APPLICATION_CREDENTIALS: *****.json
    GOOGLE_GHA_CREDS_PATH: *****.json
    CLOUDSDK_CORE_PROJECT: *****
    CLOUDSDK_PROJECT: *****
    GCLOUD_PROJECT: *****
    GCP_PROJECT: *****
    GOOGLE_CLOUD_PROJECT: *****
    ALLOWED_TOOLS: Edit,Glob,Grep,LS,Read,Write,mcp__github_file_ops__commit_files,mcp__github_file_ops__delete_files,mcp__github__update_issue_comment,Bash(make test),Bash(yarn install),Bash(yarn lint),Bash(yarn format),Bash(yarn test),Read,Edit,Write,Grep,Task,Replace
    DISALLOWED_TOOLS: WebSearch,WebFetch
    ANTHROPIC_MODEL: claude-3-7-sonnet-20250219
    GITHUB_TOKEN: ***
    AWS_REGION: 
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    AWS_SESSION_TOKEN: 
    ANTHROPIC_BEDROCK_BASE_URL: 
    ANTHROPIC_VERTEX_BASE_URL: 
    VERTEX_REGION_CLAUDE_3_5_HAIKU: 
    VERTEX_REGION_CLAUDE_3_5_SONNET: 
    VERTEX_REGION_CLAUDE_3_7_SONNET: 
    CLAUDE_CODE_ACTION: 1
    INPUT_PROMPT: 
    INPUT_PROMPT_FILE: /tmp/claude-prompts/claude-prompt.txt
    INPUT_ALLOWED_TOOLS: Edit,Glob,Grep,LS,Read,Write,mcp__github_file_ops__commit_files,mcp__github_file_ops__delete_files,mcp__github__update_issue_comment,Bash(make test),Bash(yarn install),Bash(yarn lint),Bash(yarn format),Bash(yarn test),Read,Edit,Write,Grep,Task,Replace
    INPUT_DISALLOWED_TOOLS: WebSearch,WebFetch
    INPUT_MAX_TURNS: 
    INPUT_MCP_CONFIG: {
    "mcpServers": {
      "github": {
        "command": "docker",
        "args": [
          "run",
          "-i",
          "--rm",
          "-e",
          "GITHUB_PERSONAL_ACCESS_TOKEN",
          "ghcr.io/anthropics/github-mcp-server:sha-7382253"
        ],
        "env": {
          "GITHUB_PERSONAL_ACCESS_TOKEN": "***"
        }
      },
      "github_file_ops": {
        "command": "bun",
        "args": [
          "run",
          "/home/runner/work/_actions/anthropics/claude-code-action/beta/src/mcp/github-file-ops-server.ts"
        ],
        "env": {
          "GITHUB_TOKEN": "***",
          "REPO_OWNER": "*****",
          "REPO_NAME": "***",
          "BRANCH_NAME": "claude/issue-*****",
          "REPO_DIR": "****"
        }
      }
    }
  }
    INPUT_TIMEOUT_MINUTES: 60
    ANTHROPIC_API_KEY: 
    CLAUDE_CODE_USE_BEDROCK: 
    CLAUDE_CODE_USE_VERTEX: 1
Prompt file size: 14425 bytes
Running Claude with prompt from file: /tmp/claude-prompts/claude-prompt.txt
{
  "type": "system",
  "subtype": "init",
  "session_id": "*****",
  "tools": [
    "Task",
    "Bash",
    "Glob",
    "Grep",
    "LS",
    "Read",
    "Edit",
    "MultiEdit",
    "Write",
    "NotebookRead",
    "NotebookEdit",
    "TodoRead",
    "TodoWrite",
    "mcp__github_file_ops__commit_files",
    "mcp__github_file_ops__delete_files",
    "mcp__github__add_issue_comment",
    "mcp__github__add_pull_request_review_comment",
    "mcp__github__create_branch",
    "mcp__github__create_issue",
    "mcp__github__create_or_update_file",
    "mcp__github__create_pull_request",
    "mcp__github__create_pull_request_review",
    "mcp__github__create_repository",
    "mcp__github__delete_file",
    "mcp__github__fork_repository",
    "mcp__github__get_code_scanning_alert",
    "mcp__github__get_commit",
    "mcp__github__get_file_contents",
    "mcp__github__get_issue",
    "mcp__github__get_issue_comments",
    "mcp__github__get_me",
    "mcp__github__get_pull_request",
    "mcp__github__get_pull_request_comments",
    "mcp__github__get_pull_request_files",
    "mcp__github__get_pull_request_reviews",
    "mcp__github__get_pull_request_status",
    "mcp__github__get_secret_scanning_alert",
    "mcp__github__get_tag",
    "mcp__github__list_branches",
    "mcp__github__list_code_scanning_alerts",
    "mcp__github__list_commits",
    "mcp__github__list_issues",
    "mcp__github__list_pull_requests",
    "mcp__github__list_secret_scanning_alerts",
    "mcp__github__list_tags",
    "mcp__github__merge_pull_request",
    "mcp__github__push_files",
    "mcp__github__search_code",
    "mcp__github__search_issues",
    "mcp__github__search_repositories",
    "mcp__github__search_users",
    "mcp__github__update_issue",
    "mcp__github__update_issue_comment",
    "mcp__github__update_pull_request",
    "mcp__github__update_pull_request_branch",
    "mcp__github__update_pull_request_comment"
  ],
  "mcp_servers": [
    {
      "name": "github_file_ops",
      "status": "connected"
    },
    {
      "name": "github",
      "status": "connected"
    }
  ]
}
{
  "type": "assistant",
  "message": {
    "id": "15db9fe9-e44c-46f7-aa30-8fbc8a226b70",
    "model": "<synthetic>",
    "role": "assistant",
    "stop_reason": "stop_sequence",
    "stop_sequence": "",
    "type": "message",
    "usage": {
      "input_tokens": 0,
      "output_tokens": 0,
      "cache_creation_input_tokens": 0,
      "cache_read_input_tokens": 0,
      "server_tool_use": {
        "web_search_requests": 0
      }
    },
    "content": [
      {
        "type": "text",
        "text": "API Error: No region was given. The client should be instantiated with the `region` option or the `CLOUD_ML_REGION` environment variable should be set."
      }
    ]
  },
  "session_id": "cc2f58cb-cf41-4c3d-a97d-84097ea677d1"
}
```
