### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by jphme** [anthropics/claude-code-action#9]
When running the PR review action (copy & pasted from the example + small fix): 

```
name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]  # Runs on new PRs and updates

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # Check out the code to allow git diff operations
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffs

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        with:
          # Define the review focus areas
          direct_prompt: "Review the PR changes. Focus on code quality, potential bugs, and performance issues."
          timeout_minutes: 5
          # Limited tools for safer review operations
          allowed_tools: "Bash(git diff --name-only HEAD~1),Bash(git diff HEAD~1),View,GlobTool,GrepTool"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

I get the following error:

```
Run anthropics/claude-code-action@beta
Run oven-sh/setup-bun@v2
Downloading a new version of Bun: https://bun.sh/download/1.2.11/linux/x64?avx2=true&profile=false
/usr/bin/unzip -o -q /home/runner/work/_temp/c0360474-44e6-4ca6-81b3-a9fc37250fac.zip
/home/runner/.bun/bin/bun --revision
1.2.11+cb6abd211
Run cd /home/runner/work/_actions/anthropics/claude-code-action/beta
bun install v1.2.11 (cb6abd21)

+ @types/bun@1.2.11
+ @types/node@20.17.44
+ @types/node-fetch@2.6.[12](https://github.com/xyz/actions/runs/15123782695/job/42511818577?pr=1676#step:3:13)
+ prettier@3.5.3
+ typescript@5.8.3
+ @actions/core@1.11.1
+ @actions/github@6.0.1
+ @modelcontextprotocol/sdk@1.11.0
+ @octokit/graphql@8.2.2
+ @octokit/rest@21.1.1
+ @octokit/webhooks-types@7.6.1
+ node-fetch@3.3.2
+ zod@3.24.4

141 packages installed [328.00ms]
Run bun run /home/runner/work/_actions/anthropics/claude-code-action/beta/src/entrypoints/prepare.ts
Using provided GITHUB_TOKEN for authentication
Checking permissions for actor: xyz
Permission level retrieved: admin
Actor has write access: admin
Direct prompt provided, triggering action
Actor type: User
Verified human actor: xyz
POST /repos/xyz/issues/[16](https://github.com/xyz/actions/runs/15123782695/job/42511818577?pr=1676#step:3:18)76/comments - 403 with id 4C41:31B64:D6070C6:DD8C163:682BA5E5 in 192ms
Error in initial comment: 11 |   /**
12 |    * Response object if a response was received
13 |    */
14 |   response;
15 |   constructor(message, statusCode, options) {
16 |     super(message);
         ^
HttpError: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment
   status: 403,
  request: {
  method: "POST",
  url: "https://api.github.com/repos/xyz/issues/1676/comments",
  headers: [Object ...],
  body: [Object ...],
  request: [Object ...],
},
 response: {
  url: "https://api.github.com/repos/xyz/issues/1676/comments",
  status: 403,
  headers: [Object ...],
  data: [Object ...],
},

      at new RequestError (/home/runner/work/_actions/anthropics/claude-code-action/beta/node_modules/@octokit/rest/node_modules/@octokit/core/node_modules/@octokit/request-error/dist-src/index.js:16:5)
      at fetchWrapper (/home/runner/work/_actions/anthropics/claude-code-action/beta/node_modules/@octokit/rest/node_modules/@octokit/core/node_modules/@octokit/request/dist-bundle/index.js:122:11)

POST /repos/xyz/issues/1676/comments - 403 with id 4C41:31B64:D60719A:DD8C229:682BA5E5 in [18](https://github.com/xyz/actions/runs/15123782695/job/42511818577?pr=1676#step:3:20)3ms
Error creating fallback comment: 11 |   /**
12 |    * Response object if a response was received
13 |    */
Error: Prepare step failed with error: HttpError: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment
14 |   response;
15 |   constructor(message, statusCode, options) {
16 |     super(message);
         ^
HttpError: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment
   status: [40](https://github.com/xyz/actions/runs/15123782695/job/42511818577?pr=1676#step:3:43)3,
  request: {
  method: "POST",
  url: "https://api.github.com/repos/xyz/issues/1676/comments",
  headers: [Object ...],
  body: [Object ...],
  request: [Object ...],
},
 response: {
  url: "https://api.github.com/repos/xyz/issues/1676/comments",
  status: 403,
  headers: [Object ...],
  data: [Object ...],
},

      at new RequestError (/home/runner/work/_actions/anthropics/claude-code-action/beta/node_modules/@octokit/rest/node_modules/@octokit/core/node_modules/@octokit/request-error/dist-src/index.js:16:5)
      at fetchWrapper (/home/runner/work/_actions/anthropics/claude-code-action/beta/node_modules/@octokit/rest/node_modules/@octokit/core/node_modules/@octokit/request/dist-bundle/index.js:122:11)

Error: Process completed with exit code 1.
```
